name: Latest Pre Release

on:
  release:
    types: [prereleased]

jobs:
  build-n-publish:
    name: Build and Publish masterhtermconnect
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest setuptools build wheel
        pip install -r requirements.txt

    - name: Test using Pytest
      run: |
        pytest

    - name: Build a binary wheel and a source tarball
      run: python -m build .

    - name: Publish a Python distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
