# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Lastest Release

on:
  release:
    types: [released]

jobs:
  build-n-publish:
    name: Build and Publish masterhtermconnect
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest setuptools build wheel
        pip install -r requirements.txt

    - name: Test using Pytest
      run: |
        pytest

    - name: Build a binary wheel and a source tarball
      run: python -m build .

    - name: Publish a Python distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
