# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Lastest Release

on:
  release:
    types: [released]

jobs:
  build-n-publish:
    name: Build and Publish masterhtermconnect
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest setuptools build wheel twine
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        python3 setup.py install

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test using Pytest
      run: |
        pytest

    - name: Build and upload to PyPi
      run: |
        python3 setup.py sdist bdist_wheel
        python3 -m twine upload dist/*
      env:
        TWINE_USEARNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}